version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.3
workflows:
  build:
    jobs:
      - cypress/run:
          cypress-command: 'npx cypress run --parallel --record'
          parallelism: 2
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - main
    jobs:
      - cypress/run:
          cypress-command: 'npx cypress run --parallel --record'
          parallelism: 2